services:
  casdoor:
    image: casbin/casdoor:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=release
    volumes:
      - ./conf:/conf
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true